name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images for backend
        run: |
          docker-compose -f docker-compose.yml build express

      - name: Run linting inside Docker container
        run: |
          docker-compose -f docker-compose.yml run express npm run lint  # Linting inside Docker
